### ISSUE TITLE
Steps to run inference on real case

### ISSUE THREAD

**Issue by shivanshpatel35** [3dlg-hcvc/paris#13]
Hi @SevenLJY
What are the step to run inference on a test object? The provided data has lots of components (images, train/val/test, camera poses, etc), but it is not clear what is necessary if we just want to do inference.
Thanks!

**Comment by SevenLJY** [comment]
Hi Shivansh,

This work requires per-object optimization (training) to reconstruct the object in the NeRF, and then you can render novel views or extract geometry from the field. If you'd like to reconstruct a new object using this method, you can prepare multi-view images of the object in two states by following our data format and then train the model from scratch.

Hope it helps.

**Comment by shivanshpatel35** [comment]
Should the multi-view images share the same camera extrinsics? For example, consider a drawer in two states: open and closed. Suppose we have one image for each state. Is it necessary for the images of different states to be captured from the same camera viewpoint, or can they be taken from different positions?

**Comment by SevenLJY** [comment]
It doesn't require all the views across two states to be exactly the same. But it requires the objects in two states are aligned in the world coordinate system, which can be achieved by having one shared view.

**Comment by shivanshpatel35** [comment]
Got it. Thanks!
