### ISSUE TITLE
get the texture of the reconstucted object

### ISSUE THREAD

**Issue by sky23249** [3dlg-hcvc/paris#3]
Hello, thanks for your great work! I read "Our first goal is to decouple the two parts in terms of both geometry and appearance" in paper, does that mean we can get the texture of the reconstucted object?

**Comment by SevenLJY** [comment]
Hello there! Thanks for your interest in our work. 
The appearance mentioned here is more about rendering the parts from novel views by using the neural radiance fields. It's also possible to retrieve the vertex color by querying the fields, if that is what you meant by texture.

**Comment by sky23249** [comment]
> Hello there! Thanks for your interest in our work. The appearance mentioned here is more about rendering the parts from novel views by using the neural radiance fields. It's also possible to retrieve the vertex color by querying the fields, if that is what you meant by texture.

Thanks for your reply! Yes, vertex color. I follow the command `python launch.py --test --config pretrain/storage/config/parsed.yaml --resume pretrain/storage/ckpt/last.ckpt` and get `.ply` files. But it looks colorless. If I want to get vertex color, what changes should I make? Looking forward to your reply!

**Comment by SevenLJY** [comment]
Hi @sky23249! Sorry for the late reply.

Yes, the current exported meshes are not with vertex colors. It is possible to retrieve the vertex color by querying the radiance field with the vertex position from a user-specified viewing direction. 

Hope it helps!
