### ISSUE TITLE
Classify motion type with SE model

### ISSUE THREAD

**Issue by DJNing** [3dlg-hcvc/paris#4]
Hi, I've noticed that the classification of motion type with SE(3) is not mentioned in the readme file. I wonder if you could provide some details on it? Thank you again for your great work.

**Comment by SevenLJY** [comment]
Hi there! Thanks for your interest in our work.
Training the model with the `se3.yaml` configuration basically estimates both rotation and translation params for the articulation. Once the model is trained, we can classify the motion type by thresholding the rotation angle it learned.
