### ISSUE TITLE
tinycudann installation error

### ISSUE THREAD

**Issue by aartykov** [3dlg-hcvc/paris#5]
Hello! 

I have problems with installing tinycudann. I tried both on colab and local machine with RTX 3090. Any tips to handle the error?

Thanks in advance!

**Comment by SevenLJY** [comment]
Hi! Thank you for your interest in our work. 

There could be some requirements to meet before installing `tinycudann` in terms of the platform/workstation you are working with. I'm not sure what problem you encountered during installation from your description, but I suggest following the instructions from their [repo](https://github.com/NVlabs/tiny-cuda-nn) to locate the problem and debug.
