### ISSUE TITLE
Get [Errno 2] when running demo

### ISSUE THREAD

**Issue by sablin39** [3dlg-hcvc/paris#6]
I use the command `python launch.py --train --cofig configs/revolute.yaml` and get error `[Errno 2] No such file or directory: './exp/sapien/fridge/10905/revolute/01@20231024-013154/save/it500-test'`

**Comment by SevenLJY** [comment]
Hi @sablin39. Sorry for the late reply. 

Do you still encounter this issue? I cannot reproduce this error from my side, but it's probably due to missing folder `exp` or other intermediate directories.

**Comment by xh-xh001** [comment]
> I use the command `python launch.py --train --cofig configs/revolute.yaml` and get error `[Errno 2] No such file or directory: './exp/sapien/fridge/10905/revolute/01@20231024-013154/save/it500-test'`

Have you solved this problem? I want to ask you for advice， thanks！

**Comment by SevenLJY** [comment]
Hi @xh-xh001. Thanks for your interest in our work. This bug should be fixed. Please check out the latest commit `653fb35`.
