### ISSUE TITLE
scripts to render images for *.obj file

### ISSUE THREAD

**Issue by DJNing** [3dlg-hcvc/paris#7]
Hi, would it be possible to provide scripts to render images with the preprocessed *.obj files you provided?

**Comment by DJNing** [comment]
Just a follow-up, is there a chance that the image rendering scripts will be released?

**Comment by SevenLJY** [comment]
A demo script is added to the `utils` folder. Please feel free to check out.

**Comment by shengjie-lin** [comment]
Hi, would you please tell me how to do "STEP 0: Load .obj files into the blender scene", as that part is left out in the blender_cam.py. I tried the following line of code `bpy.ops.wm.obj_import(filepath='datasets/_data/sapien/laptop/10211/textured_objs/start/start.obj')`, but the rendering would be textureless, as shown in the image.
![0001](https://github.com/user-attachments/assets/d80003ae-65dd-4ad9-903a-835d05755ded)
Looking forward to your response, thank you!

**Comment by SevenLJY** [comment]
Hi @shengjie-lin,

Thanks for reaching out. Sorry for the late late reply. 
I just updated the rendering script to include the .obj loading step and make the args more clear. Please check it out.

The code you mentioned above should load texture successfully (tested with Blender 4.1.0). I also changed the rendering engine from workbench to eevee, which should correctly render the textures.

Hope it helps.
